apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: docker-homework-service-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: dockerhomeworkapp-app
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s