apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
  namespace: default
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: psql
          image: bitnami/postgresql:latest
          command: ["/bin/sh", "-c"]
          args:
            - psql -h my-postgres-postgresql -U $POSTGRES_USER -d users -f /sql/init.sql
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: DbSettings__Username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: DbSettings__Password
          volumeMounts:
            - name: init-sql-volume
              mountPath: /sql
      volumes:
        - name: init-sql-volume
          configMap:
            name: db-init-script