apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docker-homework-app.fullname" . }}-pg-config
  labels:
    {{- include "docker-homework-app.labels" . | nindent 4 }}
data:
  DbSettings__Host: {{ .Values.pg.config.host | quote }}
  DbSettings__Database: {{ .Values.pg.config.database | quote }}
  DbSettings__Port: "{{ .Values.pg.config.port }}"