replicaCount: 2

image:
  repository: idoping/dockerhomeworkapp
  tag: 1.0.1

service:
  port: 8000

resources: {}

# Optional: default values
# resources:
#   limits:
#     cpu: 500m
#     memory: 256Mi
#   requests:
#     cpu: 250m
#     memory: 128Mi

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: arch.homework
      paths:
        - path: /otusapp/ilukin(/|$)(.*)
          pathType: ImplementationSpecific
        - path: /health
          pathType: Prefix
          
pg:
  config:
    name: pg-config
    host: my-postgres-postgresql.default.svc.cluster.local
    database: users
    port: 5432    
  secret:
    name: pg-secret
    username: iDoping
    password: Qzwxec123

initJob:
  script: |
    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        username VARCHAR(100) NOT NULL,
        email VARCHAR(100) UNIQUE NOT NULL,
        created_at TIMESTAMP DEFAULT NOW()
    );

    INSERT INTO users (username, email) VALUES
        ('alice', 'alice@example.com'),
        ('bob', 'bob@example.com'),
        ('charlie', 'charlie@example.com')
    ON CONFLICT (email) DO NOTHING;
