replicaCount: 2

image:
  repository: idoping/dockerhomeworkapp
  tag: 1.0.1

service:
  port: 8000

configMapName: pg-config
secretName: pg-secret

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: arch.homework
      paths:
        - path: /otusapp/ilukin(/|$)(.*)
          pathType: ImplementationSpecific
        - path: /health
          pathType: Prefix