apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docker-homework-app.fullname" . }}-app
  labels:
    {{- include "docker-homework-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "docker-homework-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "docker-homework-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "docker-homework-app.name" . }}-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
          - configMapRef:
              name: {{ .Values.pg.config.name }}
          - secretRef:
              name: {{ .Values.pg.secret.name }}
{{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}
          livenessProbe:
            httpGet:
              path: /health/
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/
              port: {{ .Values.service.port }}
            initialDelaySeconds: 2
            periodSeconds: 5
