apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "docker-homework-app.fullname" . }}-init
  labels:
    app.kubernetes.io/name: {{ include "docker-homework-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
        - name: psql
          image: bitnami/postgresql:latest
          command: ["/bin/sh", "-c"]
          args: ["psql -h {{ .Values.pg.config.host }} -U $POSTGRES_USER -d {{ .Values.pg.config.database }} -f /sql/init.sql"]
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pg.secret.name }}
                  key: DbSettings__Username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.pg.secret.name }}
                  key: DbSettings__Password
          volumeMounts:
            - name: init-sql-volume
              mountPath: /sql
      volumes:
        - name: init-sql-volume
          configMap:
            name: db-init-script
      restartPolicy: OnFailure
