apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
  labels:
    app.kubernetes.io/name: {{ include "docker-homework-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  init.sql: |-
{{ .Values.initJob.script | indent 4 }}
