apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pg.secret.name }}
  labels:
    {{- include "docker-homework-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DbSettings__Username: {{ .Values.pg.secret.username }}
  DbSettings__Password: {{ .Values.pg.secret.password }}