apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-homework-app.serviceName" . }}
  labels:
    {{- include "docker-homework-app.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "docker-homework-app.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.service.port }}
